name: CI

on:
    push:
        branches: [master]
        tags: ["*"]
    pull_request:
        branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
    - name: Credo
      run: mix credo --strict
    - name: Check README
      run: mix docception README.md
    - name: Formatter
      run: mix format --check-formatted
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
